### ISSUE TITLE
 Problems when using Mallet LDA via gensim

### ISSUE THREAD

**Issue by sabrinouche** [Twitter-Public-Analysis/Twitter-Public-Analysis#14]
I have a problem when I try to call Mallet LDA via gensim. I installed Mallet, set the environment variable MALLET_HOME. but it does not work
 
![Capture1](https://user-images.githubusercontent.com/68405810/87735398-b4975700-c7d5-11ea-8411-77cbe9002458.PNG)

Code :
import os
os.environ.update({'MALLET_HOME': r'C:/new_mallet/mallet-2.0.8/'})
mallet_path = 'C:/new_mallet/mallet-2.0.8/bin/mallet'  # update this path
ldamallet = gensim.models.wrappers.LdaMallet(mallet_path, corpus=corpus, num_topics=10, id2word=id2word)

Error : 
CalledProcessError                        Traceback (most recent call last)

Is there something basic missing ? Thanks in advance for all the help!

**Comment by v2thegreat** [comment]
Hey! This issue is being looked at. How are you setting up your environment? I currently have it running with conda and just doing `conda install ...` or `pip install -r requirements.txt` if you're only running on a pip environment.

Also, it might be more helpful if you posted the last few lines of the error because it generally contains more information. I'm running this on WSL, so I might not be the most helpful, but have you tried to look at this [SO post](https://stackoverflow.com/questions/55288724/gensim-mallet-calledprocesserror-returned-non-zero-exit-status) that might have the same error as you?

**Comment by v2thegreat** [comment]
Closing due to no response from @sabrinouche
