### ISSUE TITLE
Optimize Sentiment Analysis

### ISSUE THREAD

**Issue by v2thegreat** [Twitter-Public-Analysis/Twitter-Public-Analysis#9]
**Improve Sentiment Analysis Scoring Performance**

- [ ] Use `pandas.apply()` instead of traditional for loops
- [ ] Implement Dask

**Comment by RamKPrasanna** [comment]
Starting off we are aiming for a simple sentiment analysis to being with, such as using pre-trained natural language processing libraries such as TextBlob, NLTP and Flair but also non-ML algorithms such as VADER.

Due to the fact that there are no use-cases right now where we can seek validity for our programs, using different libraries in parallel will allow us to gain the most insight possible. 

Moving forward, we should train out our ML for a specific use-case and build a situation where our model can then be verified.

**Comment by erb13020** [comment]
**Improve Sentiment Analysis Scoring Performance**

- [] Use pandas.apply() instead of traditional for loops
- [] Implement Dask
